[2024-04-07T10:29:37.186+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas_1.touch_about_us manual__2024-04-07T10:19:26.360345+00:00 [queued]>
[2024-04-07T10:29:37.193+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas_1.touch_about_us manual__2024-04-07T10:19:26.360345+00:00 [queued]>
[2024-04-07T10:29:37.194+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 6
[2024-04-07T10:29:37.205+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): touch_about_us> on 2024-04-07 10:19:26.360345+00:00
[2024-04-07T10:29:37.211+0000] {standard_task_runner.py:60} INFO - Started process 756 to run task
[2024-04-07T10:29:37.213+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prioritas_1', 'touch_about_us', 'manual__2024-04-07T10:19:26.360345+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/prioritas_1_dag.py', '--cfg-path', '/tmp/tmpah6j5x7v']
[2024-04-07T10:29:37.216+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask touch_about_us
[2024-04-07T10:29:37.259+0000] {task_command.py:423} INFO - Running <TaskInstance: prioritas_1.touch_about_us manual__2024-04-07T10:19:26.360345+00:00 [running]> on host a170fefa21f9
[2024-04-07T10:29:37.313+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dzikri' AIRFLOW_CTX_DAG_ID='prioritas_1' AIRFLOW_CTX_TASK_ID='touch_about_us' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T10:19:26.360345+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T10:19:26.360345+00:00'
[2024-04-07T10:29:37.319+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-07T10:29:37.321+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch about_us/about.txt']
[2024-04-07T10:29:37.331+0000] {subprocess.py:86} INFO - Output:
[2024-04-07T10:29:37.334+0000] {subprocess.py:93} INFO - touch: cannot touch 'about_us/about.txt': No such file or directory
[2024-04-07T10:29:37.335+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-07T10:29:37.344+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-07T10:29:37.347+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=prioritas_1, task_id=touch_about_us, execution_date=20240407T101926, start_date=20240407T102937, end_date=20240407T102937
[2024-04-07T10:29:37.359+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task touch_about_us (Bash command failed. The command returned a non-zero exit code 1.; 756)
[2024-04-07T10:29:37.388+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-07T10:29:37.407+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
