[2024-04-07T10:21:31.977+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas_1.touch_about_us manual__2024-04-07T10:19:26.360345+00:00 [queued]>
[2024-04-07T10:21:31.985+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas_1.touch_about_us manual__2024-04-07T10:19:26.360345+00:00 [queued]>
[2024-04-07T10:21:31.986+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 6
[2024-04-07T10:21:31.997+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): touch_about_us> on 2024-04-07 10:19:26.360345+00:00
[2024-04-07T10:21:32.003+0000] {standard_task_runner.py:60} INFO - Started process 593 to run task
[2024-04-07T10:21:32.005+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prioritas_1', 'touch_about_us', 'manual__2024-04-07T10:19:26.360345+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/prioritas_1_dag.py', '--cfg-path', '/tmp/tmpb8y5ftye']
[2024-04-07T10:21:32.008+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask touch_about_us
[2024-04-07T10:21:32.051+0000] {task_command.py:423} INFO - Running <TaskInstance: prioritas_1.touch_about_us manual__2024-04-07T10:19:26.360345+00:00 [running]> on host a170fefa21f9
[2024-04-07T10:21:32.108+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dzikri' AIRFLOW_CTX_DAG_ID='prioritas_1' AIRFLOW_CTX_TASK_ID='touch_about_us' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T10:19:26.360345+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T10:19:26.360345+00:00'
[2024-04-07T10:21:32.111+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-07T10:21:32.113+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'touch about_us/about.txt']
[2024-04-07T10:21:32.124+0000] {subprocess.py:86} INFO - Output:
[2024-04-07T10:21:32.126+0000] {subprocess.py:93} INFO - touch: cannot touch 'about_us/about.txt': No such file or directory
[2024-04-07T10:21:32.127+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-07T10:21:32.138+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-07T10:21:32.142+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas_1, task_id=touch_about_us, execution_date=20240407T101926, start_date=20240407T102131, end_date=20240407T102132
[2024-04-07T10:21:32.151+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task touch_about_us (Bash command failed. The command returned a non-zero exit code 1.; 593)
[2024-04-07T10:21:32.180+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-07T10:21:32.202+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
