[2024-04-13T18:56:23.360+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fruits_data_pipeline.create_fruits_table manual__2024-04-13T18:47:06.154155+00:00 [queued]>
[2024-04-13T18:56:23.373+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fruits_data_pipeline.create_fruits_table manual__2024-04-13T18:47:06.154155+00:00 [queued]>
[2024-04-13T18:56:23.374+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 9
[2024-04-13T18:56:23.393+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_fruits_table> on 2024-04-13 18:47:06.154155+00:00
[2024-04-13T18:56:23.400+0000] {standard_task_runner.py:60} INFO - Started process 686 to run task
[2024-04-13T18:56:23.406+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fruits_data_pipeline', 'create_fruits_table', 'manual__2024-04-13T18:47:06.154155+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/eksplorasi.py', '--cfg-path', '/tmp/tmp94vrgwmb']
[2024-04-13T18:56:23.410+0000] {standard_task_runner.py:88} INFO - Job 180: Subtask create_fruits_table
[2024-04-13T18:56:23.491+0000] {task_command.py:423} INFO - Running <TaskInstance: fruits_data_pipeline.create_fruits_table manual__2024-04-13T18:47:06.154155+00:00 [running]> on host b46e24c16c09
[2024-04-13T18:56:23.585+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dzikri' AIRFLOW_CTX_DAG_ID='fruits_data_pipeline' AIRFLOW_CTX_TASK_ID='create_fruits_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T18:47:06.154155+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-13T18:47:06.154155+00:00'
[2024-04-13T18:56:23.590+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS fruits (
            id SERIAL PRIMARY KEY,
            name VARCHAR(255),
            calories DECIMAL,
            fat DECIMAL,
            sugar DECIMAL,
            carbohydrates DECIMAL,
            protein DECIMAL
        )
    
[2024-04-13T18:56:23.605+0000] {base.py:83} INFO - Using connection ID 'eksplorasi' for task execution.
[2024-04-13T18:56:23.624+0000] {base.py:83} INFO - Using connection ID 'eksplorasi' for task execution.
[2024-04-13T18:56:23.630+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/eksplorasi.py", line 25, in create_fruits_table
    PostgresOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-04-13T18:56:23.655+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=fruits_data_pipeline, task_id=create_fruits_table, execution_date=20240413T184706, start_date=20240413T185623, end_date=20240413T185623
[2024-04-13T18:56:23.676+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 180 for task create_fruits_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 686)
[2024-04-13T18:56:23.739+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-13T18:56:23.766+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2024-04-13T18:56:23.802+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
