[2024-04-14T14:44:35.744+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prioritas_2.write_to_csv scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T14:44:35.773+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prioritas_2.write_to_csv scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T14:44:35.775+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-04-14T14:44:35.806+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-04-13 00:00:00+00:00
[2024-04-14T14:44:35.820+0000] {standard_task_runner.py:60} INFO - Started process 101 to run task
[2024-04-14T14:44:35.829+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'prioritas_2', 'write_to_csv', 'scheduled__2024-04-13T00:00:00+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/prioritas_2_dag.py', '--cfg-path', '/tmp/tmp9t34q7_k']
[2024-04-14T14:44:35.834+0000] {standard_task_runner.py:88} INFO - Job 212: Subtask write_to_csv
[2024-04-14T14:44:35.928+0000] {task_command.py:423} INFO - Running <TaskInstance: prioritas_2.write_to_csv scheduled__2024-04-13T00:00:00+00:00 [running]> on host b46e24c16c09
[2024-04-14T14:44:36.078+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dzikri' AIRFLOW_CTX_DAG_ID='prioritas_2' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T00:00:00+00:00'
[2024-04-14T14:44:36.099+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/prioritas_2_dag.py", line 22, in write_to_csv
    with open(file_path, 'w', newline='') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/output/products.csv'
[2024-04-14T14:44:36.114+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=prioritas_2, task_id=write_to_csv, execution_date=20240413T000000, start_date=20240414T144435, end_date=20240414T144436
[2024-04-14T14:44:36.133+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 212 for task write_to_csv ([Errno 2] No such file or directory: '/data/output/products.csv'; 101)
[2024-04-14T14:44:36.163+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-14T14:44:36.196+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
