[2024-04-12T10:00:55.201+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:00:55.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:00:55.208+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:00:55.207+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:00:55.276+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:00:55.268+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:00:55.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:00:55.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.102 seconds
[2024-04-12T10:01:25.446+0000] {processor.py:161} INFO - Started process (PID=101) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:01:25.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:01:25.449+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:01:25.449+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:01:25.490+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:01:25.484+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:01:25.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:01:25.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.066 seconds
[2024-04-12T10:01:55.647+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:01:55.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:01:55.651+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:01:55.651+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:01:55.698+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:01:55.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:01:55.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:01:55.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.076 seconds
[2024-04-12T10:02:25.898+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:02:25.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:02:25.902+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:02:25.902+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:02:25.936+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:02:25.932+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:02:25.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:02:25.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.058 seconds
[2024-04-12T10:02:56.177+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:02:56.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:02:56.179+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:02:56.179+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:02:56.200+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:02:56.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:02:56.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:02:56.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.050 seconds
[2024-04-12T10:03:26.473+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:03:26.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:03:26.478+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:03:26.478+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:03:26.540+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:03:26.529+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:03:26.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:03:26.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.095 seconds
[2024-04-12T10:03:56.747+0000] {processor.py:161} INFO - Started process (PID=395) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:03:56.749+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:03:56.752+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:03:56.751+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:03:56.793+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:03:56.783+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:03:56.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:03:56.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.073 seconds
[2024-04-12T10:04:27.006+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:04:27.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:04:27.008+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:04:27.008+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:04:27.035+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:04:27.031+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:04:27.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:04:27.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.048 seconds
[2024-04-12T10:04:57.185+0000] {processor.py:161} INFO - Started process (PID=514) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:04:57.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:04:57.189+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:04:57.188+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:04:57.226+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:04:57.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:04:57.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:04:57.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.062 seconds
[2024-04-12T10:05:27.340+0000] {processor.py:161} INFO - Started process (PID=574) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:05:27.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:05:27.343+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:05:27.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:05:27.367+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:05:27.363+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:05:27.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:05:27.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.044 seconds
[2024-04-12T10:05:57.730+0000] {processor.py:161} INFO - Started process (PID=633) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:05:57.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:05:57.733+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:05:57.732+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:05:57.758+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:05:57.755+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:05:57.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:05:57.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.044 seconds
[2024-04-12T10:06:27.908+0000] {processor.py:161} INFO - Started process (PID=692) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:06:27.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:06:27.911+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:06:27.911+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:06:27.945+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:06:27.940+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:06:27.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:06:27.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.054 seconds
[2024-04-12T10:06:58.064+0000] {processor.py:161} INFO - Started process (PID=751) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:06:58.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:06:58.067+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:06:58.067+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:06:58.088+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:06:58.085+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:06:58.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:06:58.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.040 seconds
[2024-04-12T10:07:28.494+0000] {processor.py:161} INFO - Started process (PID=810) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:07:28.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:07:28.497+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:07:28.497+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:07:28.528+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:07:28.521+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:07:28.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:07:28.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.051 seconds
[2024-04-12T10:07:58.819+0000] {processor.py:161} INFO - Started process (PID=869) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:07:58.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:07:58.823+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:07:58.823+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:07:58.861+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:07:58.854+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:07:58.862+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:07:58.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.064 seconds
[2024-04-12T10:08:29.340+0000] {processor.py:161} INFO - Started process (PID=928) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:08:29.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:08:29.343+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:08:29.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:08:29.369+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:08:29.364+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:08:29.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:08:29.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.046 seconds
[2024-04-12T10:08:59.737+0000] {processor.py:161} INFO - Started process (PID=987) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:08:59.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:08:59.740+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:08:59.740+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:08:59.789+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:08:59.761+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:08:59.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:08:59.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.074 seconds
[2024-04-12T10:09:29.963+0000] {processor.py:161} INFO - Started process (PID=1047) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:09:29.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:09:29.966+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:09:29.966+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:09:29.991+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:09:29.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:09:29.991+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:09:30.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.044 seconds
[2024-04-12T10:10:00.117+0000] {processor.py:161} INFO - Started process (PID=1106) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:10:00.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:10:00.120+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:10:00.120+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:10:00.146+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:10:00.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:10:00.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:10:00.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.050 seconds
[2024-04-12T10:10:30.369+0000] {processor.py:161} INFO - Started process (PID=1165) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:10:30.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:10:30.374+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:10:30.373+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:10:30.418+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:10:30.413+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:10:30.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:10:30.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.077 seconds
[2024-04-12T10:11:00.642+0000] {processor.py:161} INFO - Started process (PID=1224) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:11:00.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:11:00.646+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:11:00.645+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:11:00.675+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:11:00.671+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:11:00.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:11:00.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.053 seconds
[2024-04-12T10:11:30.794+0000] {processor.py:161} INFO - Started process (PID=1283) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:11:30.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:11:30.798+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:11:30.797+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:11:30.825+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:11:30.822+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:11:30.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:11:30.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.048 seconds
[2024-04-12T10:12:01.080+0000] {processor.py:161} INFO - Started process (PID=1342) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:12:01.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:12:01.084+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:12:01.084+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:12:01.119+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:12:01.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:12:01.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:12:01.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.061 seconds
[2024-04-12T10:12:31.664+0000] {processor.py:161} INFO - Started process (PID=1401) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:12:31.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:12:31.668+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:12:31.667+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:12:31.711+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:12:31.705+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:12:31.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:12:31.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.071 seconds
[2024-04-12T10:13:02.104+0000] {processor.py:161} INFO - Started process (PID=1460) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:13:02.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:13:02.107+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:13:02.106+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:13:02.129+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:13:02.126+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:13:02.129+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:13:02.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.041 seconds
[2024-04-12T10:13:32.361+0000] {processor.py:161} INFO - Started process (PID=1519) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:13:32.363+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:13:32.365+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:13:32.365+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:13:32.400+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:13:32.395+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:13:32.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:13:32.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.058 seconds
[2024-04-12T10:14:02.754+0000] {processor.py:161} INFO - Started process (PID=1578) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:14:02.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:14:02.759+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:14:02.758+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:14:02.808+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:14:02.800+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:14:02.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:14:02.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.077 seconds
[2024-04-12T10:14:33.182+0000] {processor.py:161} INFO - Started process (PID=1637) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:14:33.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:14:33.187+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:14:33.186+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:14:33.227+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:14:33.224+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:14:33.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:14:33.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.066 seconds
[2024-04-12T10:15:03.303+0000] {processor.py:161} INFO - Started process (PID=1696) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:15:03.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:15:03.308+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:15:03.308+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:15:03.356+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:15:03.353+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:15:03.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:15:03.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.080 seconds
[2024-04-12T10:15:33.610+0000] {processor.py:161} INFO - Started process (PID=1756) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:15:33.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:15:33.616+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:15:33.614+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:15:33.671+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:15:33.664+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:15:33.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:15:33.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.091 seconds
[2024-04-12T10:16:03.891+0000] {processor.py:161} INFO - Started process (PID=1815) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:16:03.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:16:03.894+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:16:03.894+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:16:03.939+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:16:03.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:16:03.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:16:03.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.070 seconds
[2024-04-12T10:16:34.197+0000] {processor.py:161} INFO - Started process (PID=1874) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:16:34.199+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:16:34.200+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:16:34.200+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:16:34.232+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:16:34.228+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:16:34.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:16:34.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.056 seconds
[2024-04-12T10:17:04.513+0000] {processor.py:161} INFO - Started process (PID=1933) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:17:04.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:17:04.516+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:17:04.516+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:17:04.562+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:17:04.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:17:04.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:17:04.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.091 seconds
[2024-04-12T10:17:34.856+0000] {processor.py:161} INFO - Started process (PID=1992) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:17:34.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:17:34.858+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:17:34.858+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:17:34.893+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:17:34.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:17:34.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:17:34.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.058 seconds
[2024-04-12T10:18:05.127+0000] {processor.py:161} INFO - Started process (PID=2051) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:18:05.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:18:05.130+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:18:05.129+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:18:05.164+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:18:05.160+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:18:05.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:18:05.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.055 seconds
[2024-04-12T10:18:35.724+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:18:35.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:18:35.727+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:18:35.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:18:35.764+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:18:35.757+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:18:35.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:18:35.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.065 seconds
[2024-04-12T10:19:05.863+0000] {processor.py:161} INFO - Started process (PID=2169) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:19:05.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:19:05.865+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:19:05.865+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:19:05.899+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:19:05.891+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:19:05.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:19:05.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.056 seconds
[2024-04-12T10:19:36.132+0000] {processor.py:161} INFO - Started process (PID=2228) to work on /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:19:36.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/eksplorasi_dag.py for tasks to queue
[2024-04-12T10:19:36.135+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:19:36.135+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:19:36.193+0000] {logging_mixin.py:188} INFO - [2024-04-12T10:19:36.190+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/eksplorasi_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/eksplorasi_dag.py", line 51, in <module>
    get_data_task = SimpleHttpOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 355, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/http/operators/http.py", line 125, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 793, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to SimpleHttpOperator (task_id: get_data_from_api). Invalid arguments were:
**kwargs: {'xcom_push': True}
[2024-04-12T10:19:36.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/eksplorasi_dag.py
[2024-04-12T10:19:36.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/eksplorasi_dag.py took 0.082 seconds
